api_version = "2026-07"

[[extensions]]
name = "Quick print selected with Piqae"
handle = "piqae-bulk-quick-print"
uid = "c08af22512e96effd6df92a28c5138c9b47d14acc87e"
type = "ui_extension"

[[extensions.targeting]]
module = "./src/QuickPrintAction.jsx"
target = "admin.order-index.selection-action.render"
