packages:
  - apps/*
  - sdk/*

allowBuilds:
  '@sentry/cli': true
  core-js: false
  esbuild: true
  sharp: true

minimumReleaseAgeExclude:
  - '@posthog/browser-common@0.2.4'
  - posthog-js@1.407.6
  - '@sentry/browser-utils@10.69.0'
  - '@sentry/browser@10.69.0'
  - '@sentry/cloudflare@10.69.0'
  - '@sentry/core@10.69.0'
  - '@sentry/feedback@10.69.0'
  - '@sentry/node-core@10.69.0'
  - '@sentry/node@10.69.0'
  - '@sentry/opentelemetry@10.69.0'
  - '@sentry/replay-canvas@10.69.0'
  - '@sentry/replay@10.69.0'
  - '@sentry/server-utils@10.69.0'
  - '@sentry/svelte@10.69.0'
  - '@sentry/sveltekit@10.69.0'

onlyBuiltDependencies:
  - esbuild
  - sharp
  - unrs-resolver
