# syntax=docker/dockerfile:1.7
FROM rust:1.88-bookworm AS builder
WORKDIR /source
COPY Cargo.toml Cargo.lock ./
COPY crates crates
COPY bins bins
RUN cargo build --locked --release --bin spool-server

FROM gcr.io/distroless/cc-debian12:nonroot
COPY --from=builder /source/target/release/spool-server /usr/local/bin/spool-server
USER nonroot:nonroot
EXPOSE 8080
ENTRYPOINT ["/usr/local/bin/spool-server"]
