api_version = "2026-07"

[[extensions]]
name = "Quick print with Piqae"
handle = "piqae-order-quick-print"
uid = "ab9f9479337058e603b82a7bff9d95dc5b54d61396d8"
type = "ui_extension"

[[extensions.targeting]]
module = "./src/QuickPrintAction.jsx"
target = "admin.order-details.action.render"
