[package]
name = "spool-executor-supervisor"
version.workspace = true
edition.workspace = true
license = "Apache-2.0"
repository.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
async-trait.workspace = true
spool-agent-core = { path = "../agent-core" }
spool-domain.workspace = true
spool-executor-protocol = { path = "../executor-protocol" }
spool-protocol.workspace = true
thiserror.workspace = true
tokio.workspace = true
uuid.workspace = true

[lints]
workspace = true
