[package]
name = "spool-platform-adapters"
version.workspace = true
edition.workspace = true
license = "Apache-2.0"
repository.workspace = true
rust-version.workspace = true
publish = false

[features]
default = []
cups = []
windows-spooler = []

[dependencies]
async-trait.workspace = true
spool-protocol.workspace = true

[dev-dependencies]
spool-domain.workspace = true
tokio.workspace = true

[lints]
workspace = true
