[package]
name = "piqae-local-api"
version.workspace = true
edition.workspace = true
license = "Apache-2.0"
repository.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
axum.workspace = true
serde.workspace = true
serde_json.workspace = true
piqae-domain.workspace = true
piqae-local-ipc = { path = "../local-ipc", version = "0.1.2" }
piqae-node-runtime = { path = "../node-runtime", version = "0.1.22" }
thiserror.workspace = true
tokio.workspace = true
tower-http.workspace = true
uuid.workspace = true

[dev-dependencies]
tower.workspace = true

[lints]
workspace = true
