[package]
name = "piqae-node-client"
version.workspace = true
edition.workspace = true
license = "Apache-2.0"
repository.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
async-trait.workspace = true
piqae-local-ipc = { path = "../local-ipc", version = "0.1.2" }
piqae-node-runtime = { path = "../node-runtime", version = "0.1.21" }
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true
uuid.workspace = true

[dev-dependencies]
tempfile = "3.20.0"

[lints]
workspace = true
