[package]
name = "piqae-node-ffi"
version.workspace = true
edition.workspace = true
license = "Apache-2.0"
repository.workspace = true
rust-version.workspace = true
publish = false

[lib]
crate-type = ["rlib", "staticlib"]

[dependencies]
piqae-node-runtime = { path = "../node-runtime", version = "0.1.21" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[lints]
workspace = true
