[package]
name = "spool-executor-cups"
version.workspace = true
edition.workspace = true
license = "Apache-2.0"
repository.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
spool-domain.workspace = true
spool-executor-protocol = { path = "../executor-protocol" }
spool-protocol.workspace = true

[dev-dependencies]
spool-executor-supervisor = { path = "../executor-supervisor" }
tokio.workspace = true
uuid.workspace = true
