[package]
name = "piqae-fake-executor"
version.workspace = true
edition.workspace = true
license = "Apache-2.0"
repository.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
piqae-domain.workspace = true
piqae-executor-protocol = { path = "../executor-protocol", version = "0.1.1" }
piqae-protocol.workspace = true
uuid.workspace = true

[dev-dependencies]
piqae-executor-supervisor = { path = "../executor-supervisor", version = "0.1.1" }
tokio.workspace = true

[lints]
workspace = true
