api_version = "2026-07"

[[extensions]]
name = "Print selected orders"
handle = "piqae-bulk-order-print"
uid = "04ac0f17-d4f6-7123-977e-7cfd150d1e0000dd625e"
type = "ui_extension"

[[extensions.targeting]]
module = "./src/PrintAction.jsx"
target = "admin.order-index.selection-print-action.render"
