using System.Security.Cryptography;
using System.Text;
using Org.BouncyCastle.Math.EC.Rfc8032;

namespace Piqae.Node;

/// <summary>An opaque reference and public Ed25519 key generated by a secure host provider.</summary>
public sealed record PiqaeGeneratedConnectorKey(string Handle, byte[] PublicKey);

/// <summary>
/// Supplies Ed25519 operations to the durable native runtime without exposing
/// private key bytes through the ABI, configuration, connector records, or logs.
/// Implementations must be thread-safe; calls may arrive concurrently.
/// </summary>
public interface IPiqaeConnectorKeyProvider
{
    PiqaeGeneratedConnectorKey Generate(string scope);
    byte[] Sign(string handle, ReadOnlySpan<byte> message);
    void Delete(string handle);
}

/// <summary>
/// Windows Ed25519 provider backed by the current user's Credential Manager.
///
/// Windows CNG does not expose a documented persistent, non-exporting Ed25519
/// signing contract across Piqae's supported Windows baseline. This fallback
/// therefore stores the 32-byte Ed25519 seed as a generic Credential Manager
/// secret. Windows protects that credential at rest for the current user. Only
/// an opaque handle crosses into the durable runtime.
/// </summary>
public sealed class WindowsCredentialConnectorKeyProvider : IPiqaeConnectorKeyProvider
{
    private const string HandlePrefix = "wcred-ed25519-v1";
    private const int MaximumScopeBytes = 256;
    private const int MaximumMessageBytes = 1024 * 1024;
    private readonly string _targetPrefix;

    public WindowsCredentialConnectorKeyProvider(string installationScope)
    {
        if (!OperatingSystem.IsWindows()) throw new PlatformNotSupportedException();
        if (string.IsNullOrWhiteSpace(installationScope) || installationScope.Length > 200)
            throw new ArgumentException("The installation scope is invalid.", nameof(installationScope));
        var installationHash = Convert.ToHexString(
            SHA256.HashData(Encoding.UTF8.GetBytes(installationScope))).ToLowerInvariant();
        _targetPrefix = $"Piqae.Node/connector-ed25519/{installationHash}";
    }

    public PiqaeGeneratedConnectorKey Generate(string scope)
    {
        if (string.IsNullOrWhiteSpace(scope)
            || Encoding.UTF8.GetByteCount(scope) > MaximumScopeBytes)
            throw new ArgumentException("The connector key scope is invalid.", nameof(scope));

        var kind = KeyKind(scope);
        if (kind == "installation")
        {
            var scopeHash = Convert.ToHexString(
                SHA256.HashData(Encoding.UTF8.GetBytes(scope))).ToLowerInvariant();
            return WithNamedLock($"installation-scope.{scopeHash}", () =>
            {
                var aliasTarget = $"{_targetPrefix}/installation-alias/{scopeHash}";
                var existingHandle = WindowsCredentialStore.Read(aliasTarget);
                if (existingHandle is not null) return LoadPublicKey(existingHandle, kind);
                var generated = GenerateFresh(kind);
                try
                {
                    WindowsCredentialStore.Write(aliasTarget, generated.Handle);
                    return generated;
                }
                catch
                {
                    try { WindowsCredentialStore.DeleteRequired(Target(generated.Handle)); }
                    catch { /* Preserve the alias-write failure. */ }
                    CryptographicOperations.ZeroMemory(generated.PublicKey);
                    throw;
                }
            });
        }
        return GenerateFresh(kind);
    }

    private PiqaeGeneratedConnectorKey GenerateFresh(string kind)
    {
        var handle = $"{HandlePrefix}.{kind}.{Convert.ToHexString(RandomNumberGenerator.GetBytes(16)).ToLowerInvariant()}";
        var target = Target(handle);
        var seed = RandomNumberGenerator.GetBytes(Ed25519.SecretKeySize);
        var publicKey = new byte[Ed25519.PublicKeySize];
        try
        {
            Ed25519.GeneratePublicKey(seed, 0, publicKey, 0);
            WithHandleLock(handle, () =>
            {
                WindowsCredentialStore.WriteBytes(target, seed);
                var verified = WindowsCredentialStore.ReadBytes(target)
                    ?? throw new CryptographicException("The connector key could not be verified in Windows Credential Manager.");
                try
                {
                    if (!CryptographicOperations.FixedTimeEquals(seed, verified))
                        throw new CryptographicException("Windows Credential Manager returned different connector key material.");
                }
                finally { CryptographicOperations.ZeroMemory(verified); }
            });
            return new(handle, publicKey);
        }
        catch
        {
            try { WindowsCredentialStore.DeleteRequired(target); }
            catch { /* Preserve the original failure without disclosing the target or key. */ }
            CryptographicOperations.ZeroMemory(publicKey);
            throw;
        }
        finally { CryptographicOperations.ZeroMemory(seed); }
    }

    private PiqaeGeneratedConnectorKey LoadPublicKey(string handle, string expectedKind)
    {
        ValidateHandle(handle);
        if (!handle.StartsWith($"{HandlePrefix}.{expectedKind}.", StringComparison.Ordinal))
            throw new CryptographicException("The stored connector key alias has the wrong key class.");
        return WithHandleLock(handle, () =>
        {
            var seed = WindowsCredentialStore.ReadBytes(Target(handle))
                ?? throw new CryptographicException("The stored connector key alias is unavailable.");
            try
            {
                if (seed.Length != Ed25519.SecretKeySize)
                    throw new CryptographicException("The connector key is invalid.");
                var publicKey = new byte[Ed25519.PublicKeySize];
                Ed25519.GeneratePublicKey(seed, 0, publicKey, 0);
                return new PiqaeGeneratedConnectorKey(handle, publicKey);
            }
            finally { CryptographicOperations.ZeroMemory(seed); }
        });
    }

    public byte[] Sign(string handle, ReadOnlySpan<byte> message)
    {
        ValidateHandle(handle);
        if (message.Length > MaximumMessageBytes)
            throw new ArgumentOutOfRangeException(nameof(message), "The signing message is too large.");
        var messageBytes = message.ToArray();
        try
        {
            return WithHandleLock(handle, () =>
            {
                var seed = WindowsCredentialStore.ReadBytes(Target(handle))
                    ?? throw new CryptographicException("The connector key is unavailable.");
                try
                {
                    if (seed.Length != Ed25519.SecretKeySize)
                        throw new CryptographicException("The connector key is invalid.");
                    var signature = new byte[Ed25519.SignatureSize];
                    Ed25519.Sign(seed, 0, messageBytes, 0, messageBytes.Length, signature, 0);
                    return signature;
                }
                finally { CryptographicOperations.ZeroMemory(seed); }
            });
        }
        finally { CryptographicOperations.ZeroMemory(messageBytes); }
    }

    public void Delete(string handle)
    {
        ValidateHandle(handle);
        if (handle.StartsWith($"{HandlePrefix}.installation.", StringComparison.Ordinal))
            throw new InvalidOperationException("The stable installation key cannot be deleted as a connector key.");
        WithHandleLock(handle, () => WindowsCredentialStore.DeleteRequired(Target(handle)));
    }

    internal void DeleteInstallationForTests(string scope)
    {
        if (KeyKind(scope) != "installation") throw new ArgumentException("Expected an installation scope.", nameof(scope));
        var scopeHash = Convert.ToHexString(
            SHA256.HashData(Encoding.UTF8.GetBytes(scope))).ToLowerInvariant();
        WithNamedLock($"installation-scope.{scopeHash}", () =>
        {
            var aliasTarget = $"{_targetPrefix}/installation-alias/{scopeHash}";
            var handle = WindowsCredentialStore.Read(aliasTarget);
            if (handle is not null)
            {
                ValidateHandle(handle);
                WindowsCredentialStore.DeleteRequired(Target(handle));
            }
            WindowsCredentialStore.DeleteRequired(aliasTarget);
        });
    }

    private static string KeyKind(string scope)
    {
        if (scope.StartsWith("installation/", StringComparison.Ordinal)
            && scope.Length > "installation/".Length) return "installation";
        if (scope.StartsWith("connector/", StringComparison.Ordinal)
            && scope.Length > "connector/".Length) return "connector";
        throw new ArgumentException("The connector key scope is unsupported.", nameof(scope));
    }

    private string Target(string handle) => $"{_targetPrefix}/{handle}";

    private static void ValidateHandle(string handle)
    {
        if (string.IsNullOrWhiteSpace(handle)
            || handle.Length > 255
            || (!handle.StartsWith($"{HandlePrefix}.connector.", StringComparison.Ordinal)
                && !handle.StartsWith($"{HandlePrefix}.installation.", StringComparison.Ordinal))
            || handle.Any(character => !char.IsAsciiLetterOrDigit(character) && character is not '.' and not '-'))
            throw new ArgumentException("The connector key handle is invalid.", nameof(handle));
    }

    private static T WithHandleLock<T>(string handle, Func<T> operation) =>
        WithNamedLock($"handle.{handle}", operation);

    private static T WithNamedLock<T>(string lockScope, Func<T> operation)
    {
        var mutexName = $@"Local\Piqae.Node.connector-key.{Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(lockScope)))}";
        using var mutex = new Mutex(false, mutexName);
        var ownsMutex = false;
        try
        {
            try { ownsMutex = mutex.WaitOne(TimeSpan.FromSeconds(5)); }
            catch (AbandonedMutexException) { ownsMutex = true; }
            if (!ownsMutex) throw new TimeoutException("Timed out waiting for the connector-key lock.");
            return operation();
        }
        finally { if (ownsMutex) mutex.ReleaseMutex(); }
    }

    private static void WithHandleLock(string handle, Action operation) =>
        WithHandleLock(handle, () => { operation(); return true; });

    private static void WithNamedLock(string lockScope, Action operation) =>
        WithNamedLock(lockScope, () => { operation(); return true; });
}
